### ISSUE TITLE
How to show the tray again? (Keyboard shortcut)

### ISSUE THREAD

**Issue by rhoconlinux** [jonnylamb/shell-hide-legacy-tray#1]
Hi! awesome work! Thank you very much. 

I'm thinking... is there a way to have the tray back without disabling the extension? 
A keyboard shortcut would be a great alternative to show "just once" the tray every time the shortut is invoked. In this way the extension will be really powerful cause there is no need to remove/disable it if you casually run an app that needs tray access. 

Cheers!

**Comment by jonnylamb** [comment]
Good idea! Fancy writing a patch? :smile:

**Comment by rhoconlinux** [comment]
I really don't know a word of JS but... I think attaching a keyboard shortcut to switch the extension on/off will do it perfectly ^_^. If you need a hand I can check other extensions to try to see how to make a shortcut :dancers: 
:rabbit: 
Cheers! :)

**Comment by jonnylamb** [comment]
#3 added a shortcut to do exactly this. Thanks, @pbogut!
